<?php

namespace App\Rules;

use Closure;
use Illuminate\Contracts\Validation\ValidationRule;

class NoBadWords implements ValidationRule
{
    protected array $badWords = [
        'địt',
        'cặc',
        'lồn',
        'buồi',
        'đụ',
        'đéo',
        'đcm',
        'đmm',
        'loz',
        'clgt',
        'đm',
        'clm',
        'vl',
        'địt mẹ',
        'cặc mẹ',
        'lồn mẹ',
        'buồi mẹ',
        'đụ mẹ',
        'địt con',
        'địt cái',
        'đéo mẹ',
        'địt mày',
        'cặc cụ',
        'lồn cụ',
        'đm mẹ',
        'đcm mẹ',
        'địt bố',
        'địt bố mày',
        'địt ông',
        'địt cha',
        'đéo con',
        'đéo cái',
        'lồn lợn',
        'địt lợn',
        'cặc lợn',
        'buồi lợn',
        'đụ lợn',
        'đm con',
        'đm cái',
        'đéo bố',
        'đéo cha',
        'đéo ông',
        'đm ông',
        'đéo mợ',
        'đéo dì',
        'đéo dượng',
        'địt dượng',
        'cặc dượng',
        'buồi dượng',
        'đm dượng',
        'đéo thằng',
        'đéo con chó',
        'địt con chó',
        'địt con đĩ',
        'đéo con đĩ',
        'địt mẹ mày',
        'địt con mẹ',
        'địt mẹ con',
        'địt con mày',
        'cặc chó',
        'lồn chó',
        'buồi chó',
        'đụ chó',
        'đéo chó',
        'địt chó',
        'đm chó',
        'clgt mẹ',
        'đm mày',
        'đm tao',
        'đm chúng mày',
        'đm chúng tao',
        'đéo chúng mày',
        'đéo chúng tao',
        'địt lồn',
        'địt mẹ lồn',
        'địt mẹ lồn mày',
        'cặc mẹ lồn',
        'đm mẹ lồn',
        'đm con lồn',
        'đm con cặc',
        'đm con buồi',
        'đm con đĩ',
        'đm con đực',
        'đéo con đực',
        'đéo con đĩ',
        'đéo con buồi',
        'đéo con cặc',
        'địt đực',
        'cặc đực',
        'lồn đực',
        'buồi đực',
        'đụ đực',
        'đéo đực',
        'đm đực',
        'clgt đực',
        'đéo clgt',
        'đéo clgm',
        'clgm',
        'đéo clgm',
        'đéo clgt mẹ',
        'địt clgt',
        'địt clgm',
        'đéo mẹ mày',
        'địt mẹ mày',
        'địt con mẹ mày',
        'địt mẹ con mày',
    ];

    public function validate(string $attribute, mixed $value, Closure $fail): void
    {
        $lower = mb_strtolower($value, 'UTF-8');

        foreach ($this->badWords as $word) {
            if (str_contains($lower, $word)) {
                $fail("Trường :attribute chứa từ ngữ không phù hợp.");
                return;
            }
        }
    }
}
