name: Deploy Backend to Pion Hosting via FTP

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️ Checkout source code
      - name: Get latest code
        uses: actions/checkout@v4

      # # 2️ Deploy to Pion Hosting via FTP - commented to prevent to deploy on every push, can be uncommented when ready to deploy  
      # - name: Deploy to Pion Hosting via FTP
      #   uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      #   with:
      #     server: ${{ secrets.FTP_SERVER }}
      #     username: ${{ secrets.FTP_USERNAME }}
      #     password: ${{ secrets.FTP_PASSWORD }}
      #     protocol: ftp
      #     port: 21
      #     local-dir: ./
      #     server-dir: /
      #     dangerous-clean-slate: false
      #     exclude: |
      #       **/.git*
      #       **/.github/**
      #       **/node_modules/**
      #       **/tests/**
      #       **/.env
      #       **/vendor/**
